<?php

namespace Tests;

use App\Product;
use App\Voucher;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use App\Discount;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;
    use DatabaseMigrations;
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Discount::insert([['discount' => '10'], ['discount' => '15'], ['discount' => '20'], ['discount' => '25']]);

        Voucher::insert(['discount_id' => 1, 'start_date' => '2017-01-01', 'end_date' => '2017-12-12' ]);
        Voucher::insert(['discount_id' => 2, 'start_date' => '2017-01-01', 'end_date' => '2017-12-12' ]);
        Voucher::insert(['discount_id' => 3, 'start_date' => '2017-01-01', 'end_date' => '2017-12-12' ]);
        Voucher::insert(['discount_id' => 4, 'start_date' => '2017-01-01', 'end_date' => '2017-12-12' ]);
        Voucher::insert(['discount_id' => 4, 'start_date' => '2017-01-01', 'end_date' => '2017-12-12' ]);

        Product::insert(['name' => 'test product #1', 'price' => 100]);
        Product::insert(['name' => 'test product #2', 'price' => 200]);
    }
}
